# Generated by Django 3.0.6 on 2020-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=1024, verbose_name='Описание задачи')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания задачи')),
                ('status', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(verbose_name='дата выполнения')),
            ],
        ),
    ]
